"""Generate the risk-constraint Markdown table from current config and code.

Reads `config/runtime.env` and instantiates `council.portfolio.PortfolioConstructor`
to obtain the live default values, then renders a Markdown fragment delimited
by ``<!-- BEGIN risk-table -->`` / ``<!-- END risk-table -->`` markers.

Usage
-----
Inspect what would be written::

    python scripts/generate_risk_doc.py --dry-run

Update README.md in place between markers (creates them if missing)::

    python scripts/generate_risk_doc.py --inplace
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

BEGIN = "<!-- BEGIN risk-table -->"
END = "<!-- END risk-table -->"


def _load_runtime_env(env_path: Path) -> None:
    if not env_path.exists():
        return
    for line in env_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, _, v = line.partition("=")
        os.environ.setdefault(k.strip(), v.strip())


def render_table() -> str:
    repo = Path(__file__).resolve().parent.parent
    _load_runtime_env(repo / "config" / "runtime.env")
    sys.path.insert(0, str(repo))

    from council.portfolio import PortfolioConstructor

    pc = PortfolioConstructor()

    rows = [
        ("Max position per ticker", f"{pc.max_position:.0%}", "MLCOUNCIL_MAX_POSITION_SIZE"),
        ("Min position floor", f"{pc.min_position:.0%}", "(constant)"),
        ("Max one-way turnover", f"{pc.max_turnover:.0%}", "MLCOUNCIL_MAX_TURNOVER"),
        ("Max annualised portfolio vol", f"{pc.max_vol_ann:.0%}", "(constant)"),
        ("Sector cap (dynamic floor)", f"{pc.sector_cap:.0%}", "(constant, may relax)"),
        ("Beta neutrality", str(pc.beta_neutral), "(constant)"),
        ("Max |portfolio beta|", f"{pc.max_beta_exposure:.2f}", "(constant)"),
        ("Commission", f"{pc.commission_bps:.1f} bps", "MLCOUNCIL_COMMISSION_BPS"),
        ("Slippage (static lookup)", f"{pc.slippage_bps:.1f} bps", "MLCOUNCIL_SLIPPAGE_BPS"),
        ("Transaction-cost penalty λ", f"{pc.tc_lambda:.2f}", "(constant)"),
        ("Min signal strength (|z|)", f"{pc.min_signal_strength:.2f}", "MLCOUNCIL_MIN_SIGNAL_STRENGTH"),
        ("Drawdown circuit breaker", f"{pc.max_drawdown_threshold:.0%}", "MLCOUNCIL_MAX_DRAWDOWN_PCT"),
        ("Crypto enabled", str(pc.crypto_enabled), "MLCOUNCIL_CRYPTO_ENABLED"),
        ("Max crypto position", f"{pc.max_crypto_position:.0%}", "MLCOUNCIL_MAX_CRYPTO_POSITION_SIZE"),
        ("Max crypto turnover", f"{pc.max_crypto_turnover:.0%}", "MLCOUNCIL_MAX_CRYPTO_TURNOVER"),
    ]

    lines: list[str] = []
    lines.append(BEGIN)
    lines.append("")
    lines.append("_Auto-generated by `scripts/generate_risk_doc.py` — do not edit by hand._")
    lines.append("")
    lines.append("| Constraint | Default | Source |")
    lines.append("|---|---|---|")
    for label, value, source in rows:
        lines.append(f"| {label} | {value} | `{source}` |")

    lines.append("")
    lines.append("Size-adaptive tiers (from `PortfolioConstructor._get_portfolio_tier`):")
    lines.append("")
    lines.append("| Portfolio value | Positions | Max pos. | Max turnover | Budget |")
    lines.append("|---|---|---|---|---|")
    lines.append("| < $5 000 | 3 | 45% | 50% | 100% |")
    lines.append("| $5 000 – $25 000 | 5 | 25% | 40% | 100% |")
    lines.append("| $25 000 – $100 000 | 10 | 15% | 35% | 100% |")
    lines.append("| ≥ $100 000 | 12 | 13% | 30% | 85% |")
    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def _replace_block(text: str, block: str) -> str:
    pattern = re.compile(rf"{re.escape(BEGIN)}.*?{re.escape(END)}", re.DOTALL)
    if pattern.search(text):
        return pattern.sub(block, text)
    return text.rstrip() + "\n\n" + block + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--inplace", action="store_true", help="rewrite README.md between markers")
    parser.add_argument("--dry-run", action="store_true", help="print to stdout (default)")
    parser.add_argument("--readme", default="README.md")
    args = parser.parse_args()

    block = render_table()

    if args.inplace:
        path = Path(args.readme)
        original = path.read_text(encoding="utf-8") if path.exists() else ""
        updated = _replace_block(original, block)
        if updated != original:
            path.write_text(updated, encoding="utf-8")
            print(f"updated {path}")
        else:
            print(f"no changes for {path}")
    else:
        print(block)
    return 0


if __name__ == "__main__":
    sys.exit(main())
